[build]
  functions = "netlify/functions"

[functions.proxy-image]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**"]
  environment = { NODE_OPTIONS = "--max-old-space-size=512" }